//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odontologia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OdontologicaEntities3 : DbContext
    {
        public OdontologicaEntities3()
            : base("name=OdontologicaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Boleta> Boleta { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Familia> Familia { get; set; }
        public virtual DbSet<OrdenPedido> OrdenPedido { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<RecepcionProducto> RecepcionProducto { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
    
        public virtual ObjectResult<sp_listar_recepciones_Result> sp_listar_recepciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listar_recepciones_Result>("sp_listar_recepciones");
        }
    }
}
