//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odontologia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenPedido
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Cantidad { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdProveedor { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
