//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odontologia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.OrdenPedido = new HashSet<OrdenPedido>();
            this.RecepcionProducto = new HashSet<RecepcionProducto>();
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> PrecioCompra { get; set; }
        public Nullable<int> PrecioVenta { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> StockCritico { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdFamilia { get; set; }
    
        public virtual Familia Familia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenPedido> OrdenPedido { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecepcionProducto> RecepcionProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios { get; set; }
    }
}
